drop table T_ACCOUNT if exists
drop table T_TOOT if exists

/*Tables*/
create table T_TOOT (tootId bigint generated by default as identity (start with 1), tootMessage varchar(200), custId bigint, primary key (tootId))
create table T_ACCOUNT (id bigint generated by default as identity (start with 1), userName varchar(20), firstName varchar(50), lastName varchar(50), email varchar(50), password varchar(100), accountType varchar(10), primary key (id))

/* Alters */
alter table T_TOOT add foreign key (custId) references T_ACCOUNT(id)